#!/usr/bin/env python3
"""Check that the site's outbound links still resolve.

`verify.py` proves the *internal* links point at files that exist; nothing
proved the *external* ones do. They come from episode descriptions in the RSS
feed, where the author's text frequently runs straight into a URL
("…to Python.https://github.com/suned/statelessPrior attempt at…"), so a link
can be wrong the day it is written.

    python3 .scripts/check_links.py            # every external link (cached)
    python3 .scripts/check_links.py --changed  # only links in edited pages
    python3 .scripts/check_links.py --all      # ignore the cache, recheck all

Results are cached in .scripts/.cache/links.json for FRESH_DAYS, so a routine
run only touches the network for links it has never seen. Failures are never
cached, so a broken link stays reported until it is fixed.

Exit status is 1 when a link is definitively broken (404/410, dead host, bad
URL). Hosts that block automated requests are reported as "unverified" and do
not fail the run — see BOT_HOSTILE.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone

import hpp
from hpp import SITE

FRESH_DAYS = 30
TIMEOUT = 20
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/125.0 Safari/537.36")

# Share buttons: generated by social.py, aimed at the sharer's own composer.
# They are never "content" links and several of the hosts 999 a bare request.
SHARE_URLS = re.compile(
    r"^https://("
    r"bsky\.app/intent/|x\.com/intent/|www\.linkedin\.com/sharing/|"
    r"news\.ycombinator\.com/submitlink|www\.reddit\.com/submit)")

# Hosts that answer robots with a challenge, a login wall or a plain 403 no
# matter how the request is shaped. A failure here says nothing about the link,
# so report it and move on rather than failing the run.
BOT_HOSTILE = (
    "x.com", "twitter.com", "www.linkedin.com", "linkedin.com",
    "www.reddit.com", "reddit.com", "music.amazon.com", "www.amazon.com",
    "medium.com", "www.instagram.com", "discord.com", "discord.gg",
    "www.udemy.com", "twitter.x.com",
)
# Only statuses that mean "this URL is wrong". A 403/429/500 says something
# about the server or its bot policy, not about the link.
BROKEN_STATUS = {404, 410}


def cache_path() -> str:
    os.makedirs(hpp.CACHE, exist_ok=True)
    return os.path.join(hpp.CACHE, "links.json")


def load_cache() -> dict[str, dict]:
    try:
        with open(cache_path(), encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}


def save_cache(cache: dict[str, dict]) -> None:
    with open(cache_path(), "w", encoding="utf-8") as f:
        json.dump(cache, f, indent=1, sort_keys=True)


def fresh(entry: dict) -> bool:
    if entry.get("state") != "ok":
        return False  # never trust a cached failure
    try:
        when = datetime.fromisoformat(entry["checked"])
    except (KeyError, ValueError):
        return False
    return (datetime.now(timezone.utc) - when).days < FRESH_DAYS


def host_of(url: str) -> str:
    try:
        return urllib.parse.urlsplit(url).hostname or ""
    except ValueError:
        return ""


# Invisible characters swept up when a description's text runs into its URL.
INVISIBLE = re.compile(r"[​-‏⁠⁦-⁩﻿­]")
# A DNS label is alphanumerics and inner hyphens — nothing else, and it may not
# end in one, so "wintertechforum.com-" and "ollama.com\" are wrong on sight.
HOSTNAME = re.compile(r"^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$")


def bad_id(url: str) -> str:
    """Whether an ID-shaped URL has the wrong shape.

    YouTube and Spotify answer a mangled ID with a 200 and an error page, so
    status alone would let "…watch?v=VBT0j14rn5c-" through. Their IDs are
    fixed-width, which is the tell.
    """
    parts = urllib.parse.urlsplit(url)
    host = (parts.hostname or "").removeprefix("www.").removeprefix("m.")
    if host == "youtube.com" and parts.path == "/watch":
        video = urllib.parse.parse_qs(parts.query).get("v", [""])[0]
        if not re.fullmatch(r"[\w-]{11}", video):
            return f"YouTube video ids are 11 characters, not {video!r}"
    if host == "youtu.be":
        video = parts.path.strip("/")
        if video and not re.fullmatch(r"[\w-]{11}", video):
            return f"YouTube video ids are 11 characters, not {video!r}"
    if host == "open.spotify.com":
        segments = [p for p in parts.path.split("/") if p]
        if len(segments) == 2 and not re.fullmatch(r"[A-Za-z0-9]{22}", segments[1]):
            return f"Spotify ids are 22 characters, not {segments[1]!r}"
    return ""


def malformed(url: str) -> str:
    """Why this can't be a real URL, or "" if it might be."""
    if bad := INVISIBLE.search(url):
        return f"invisible character U+{ord(bad.group()):04X} in the URL"
    host = host_of(url)
    if not host:
        return "no hostname"
    if not HOSTNAME.match(host):
        return f"not a valid hostname: {host!r}"
    return bad_id(url)


def links_in(paths: list[str]) -> dict[str, list[str]]:
    """External URL -> the pages that link to it."""
    found: dict[str, list[str]] = {}
    for path in paths:
        doc = open(path, encoding="utf-8").read()
        for m in re.finditer(r'(?:href|src)="(https?://[^"]+)"', doc):
            url = hpp.unesc(m.group(1))
            if url.startswith(SITE) or SHARE_URLS.match(url):
                continue
            found.setdefault(url, []).append(path)
    return found


def request(url: str, method: str) -> tuple[str, str]:
    """(state, detail) for one request. state is ok | broken | unverified."""
    req = urllib.request.Request(url, method=method, headers={
        "User-Agent": UA,
        "Accept": "text/html,application/xhtml+xml,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
    })
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT) as r:
            if method == "GET":
                r.read(2048)
            return "ok", str(r.status)
    except urllib.error.HTTPError as e:
        state = "broken" if e.code in BROKEN_STATUS else "unverified"
        return state, f"HTTP {e.code}"
    except urllib.error.URLError as e:
        reason = e.reason
        if isinstance(reason, socket.gaierror):
            return "broken", "host does not resolve"
        return "unverified", f"{type(reason).__name__}: {reason}"
    except (ValueError, socket.timeout, OSError) as e:
        return "unverified", f"{type(e).__name__}: {e}"


def github_probe(url: str) -> tuple[str, str] | None:
    """Ask git whether a github.com repo exists.

    GitHub answers datacenter IPs with a 403 often enough that a plain request
    proves nothing — but `git ls-remote` speaks a protocol GitHub always
    serves, and a repo that does not exist is exactly the mistake this tool is
    looking for (`suned/statelessPrior` for `suned/stateless`).
    """
    parts = urllib.parse.urlsplit(url)
    if parts.hostname not in ("github.com", "www.github.com"):
        return None
    segments = [p for p in parts.path.split("/") if p]
    if len(segments) < 2:
        return None
    owner, repo = segments[0], segments[1].removesuffix(".git")
    try:
        done = subprocess.run(
            ["git", "ls-remote", f"https://github.com/{owner}/{repo}"],
            capture_output=True, timeout=60,
            env={**os.environ, "GIT_TERMINAL_PROMPT": "0"})
    except (OSError, subprocess.TimeoutExpired):
        return None
    if done.returncode != 0:
        return "broken", f"no such repo: {owner}/{repo}"
    if len(segments) == 2:
        return "ok", "git ls-remote"
    return "unverified", f"{owner}/{repo} exists, path unchecked"


def check(url: str) -> dict:
    """HEAD first — many hosts refuse it, so fall back to a truncated GET."""
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    if reason := malformed(url):
        return {"state": "broken", "detail": reason, "checked": now}
    state, detail = request(url, "HEAD")
    if state != "ok":
        state, detail = request(url, "GET")
    if state != "ok":
        state, detail = github_probe(url) or (state, detail)
    if state == "broken" and host_of(url) in BOT_HOSTILE:
        state, detail = "unverified", f"{detail} (host blocks robots)"
    return {"state": state, "detail": detail, "checked": now}


def changed_pages() -> list[str]:
    """HTML pages edited but not yet committed, plus new untracked ones."""
    try:
        out = subprocess.run(["git", "status", "--porcelain", "--", "*.html"],
                             capture_output=True, text=True, check=True).stdout
    except (subprocess.CalledProcessError, FileNotFoundError):
        return []
    paths = []
    for line in out.splitlines():
        name = line[3:].split(" -> ")[-1].strip().strip('"')
        if name.endswith(".html") and os.path.exists(name):
            paths.append(os.path.normpath(name))
    return sorted(set(paths))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--changed", action="store_true",
                    help="only pages with uncommitted edits")
    ap.add_argument("--all", action="store_true", help="ignore the cache")
    ap.add_argument("--jobs", type=int, default=8, help="parallel requests")
    ap.add_argument("pages", nargs="*", help="specific pages to check")
    args = ap.parse_args()

    hpp.require_root()
    if args.pages:
        paths = [os.path.normpath(os.path.relpath(os.path.abspath(p), hpp.ROOT))
                 for p in args.pages]
    elif args.changed:
        paths = changed_pages()
        if not paths:
            print("no edited pages — nothing to check")
            return
    else:
        paths = hpp.pages()

    found = links_in(paths)
    cache = {} if args.all else load_cache()
    todo = [u for u in found if not fresh(cache.get(u, {}))]
    print(f"pages: {len(paths)}  links: {len(found)}  to check: {len(todo)}")

    started = time.time()
    if todo:
        with ThreadPoolExecutor(max_workers=args.jobs) as pool:
            for url, result in zip(todo, pool.map(check, todo)):
                cache[url] = result
        save_cache(cache)

    broken = {u: cache[u] for u in found if cache[u]["state"] == "broken"}
    unverified = {u: cache[u] for u in found if cache[u]["state"] == "unverified"}

    if unverified:
        print(f"\n{len(unverified)} unverified (host refused an automated "
              f"request — check by hand if it matters):")
        for url, r in sorted(unverified.items()):
            print(f" ? {url}  [{r['detail']}]")
    if broken:
        print(f"\n{len(broken)} BROKEN:")
        for url, r in sorted(broken.items()):
            print(f" x {url}  [{r['detail']}]")
            for page in found[url]:
                print(f"     {page}")
        sys.exit(1)
    print(f"\nOK — {len(found) - len(unverified)} links resolve "
          f"({time.time() - started:.0f}s)")


if __name__ == "__main__":
    main()
